spring.application.name=roadSurvey

server.port= 9090

# Database configuration will be overridden by Docker Compose
spring.datasource.url=jdbc:postgresql://localhost:5432/roadsurveydb
spring.datasource.username=postgres
spring.datasource.password=Crosshood@442
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true